### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by rauchp**
New UI for this bounty: https://github.com/near/bounties/issues/44

Completed:
- [x] Wallet Login (I'm gonna do this next if no one else does, should just be copy and paste from Create Near App)
- [x] Wire Swap and Provide Liquidity Contracts from https://github.com/ref-finance/ref-contracts
- [x] Add list of liquidity tokens we'll initially support to show on "Provide Liquidity" page
- [x] Wire `ft_transfer_call` and `withdraw` calls 

If anyone wants to contribute, here's what we still need:
- [x] We need to grab how much liquidity was placed into each pair, and only show the  "Remove Liquidity" option if they actually provided any.
- [x] Grabbing coin list directly from contract is slow. We might want to either cache token metadata, or move the call for the list to a backend.
- [x] We need to get whether or not a user is registered with the contract, and call it one-time if they aren't.
- [x] The token metadata icon is useless. The frontend is probably gonna need custom images for the icons we can easily get like USDC.
- [x] Wire remove liquidity (function call already in code - just not called anywhere.)

### CODE REVIEW

**Comment by rauchp** [comment]
Screen Shot 2021-03-16 at 6 59 11 PM


Screen Shot 2021-03-16 at 6 59 14 PM

Screen Shot 2021-03-16 at 6 59 17 PM

Screen Shot 2021-03-16 at 6 59 20 PM

Screenshots of UI so far. Just realized the deposit / withdraw on portfolio is missing. Will add ASAP

**Comment by lau-bin** [comment]
Hi, any update on this? I want to start with some item

**Comment by rauchp** [comment]
already wired, pushing today.

**Comment by lau-bin** [comment]
Alright i will check it later, if there are more stuff on the list i would like to contribute

**Comment by ilblackdragon** [comment]
Removed contract/ folder as it's not needed here. Added license files.

**Comment by rauchp** [comment]
- I added a call to use `storage_balance_of`, the only thing or the third checkbox is a modal that appears when you're signed in and your storage balance total is 0. From there we already have the code to register a user through storage deposit, so just need to wire that.

- For the metadata, we just need to fill in the default coin list with better images.

**Comment by ilblackdragon** [comment]
Let's change color scheme a bit so it looks a bit 

UI bugs:
 - pull the metadata for tokens that are in whitelist and save in localstorage
        - this metadata should be used to format balances
  - menu
    -   highlighting over menu item should have backgound
    -   currently selected menu should have a background
 - portfolio
     - Title is too high
     -  when not logged in, show "Login with NEAR" button
     -  deposit / withdraw should be highlighted as buttons
     -  I think list of tokens is better than cards - cards don't scale very well. Can also have buttons like withdraw on them directly. And $ amounts for them.
 - swap page
   - when not logged in, should replace SWAP button with "Login with NEAR"
   - image is over the swap UI
   - clicking on MAX doesn't work
   - clicking on balance should also work as MAX
   - when opening swap & logged in - show wNEAR or first token in portfolio
   - when only one token is selected - show "SELECT A TOKEN" in the button
 - liquidity
    - rename to "Pools"
    - when screen in small it all collides
    - liquidity is in the pools info: it has both sides of tokens in `amounts`. Multiple by current price of these tokens.
    - currently clicking in is still not pools info but single token info
    - there is a random 0 on top of liquidity display
Screen Shot 2021-03-26 at 1 41 27 AM

Warning: account ids on NEAR can be up to 64 characters. We have UI component that decides how to show them based on what kind of account id it is.

For test, we can add some USDT/USDC metadata tokens on TestNet to make it easier to test.

**Comment by rauchp** [comment]
Knocked out the following:

- [x] highlighting over menu item should have backgound
- [x] currently selected menu should have a background
- [x] Title is too high
- [x] when not logged in, show "Login with NEAR" button
- [x] deposit / withdraw should be highlighted as buttons
- [x] I think list of tokens is better than cards - cards don't scale very well. Can also have buttons like withdraw on them directly. 
- [x] image is over the swap UI
- [x] clicking on MAX doesn't work
- [x] when only one token is selected - show "SELECT A TOKEN" in the button
- [x] rename to "Pools"
- [x] when screen in small it all collides
- [x] there is a random 0 on top of liquidity display

**Review by thisisjoshford — APPROVED** [review]

**Pull request merged**
