### PR TITLE
Ukrainian localisation introduced

### PR DESCRIPTION
**Pull request by zavodil**

### CODE REVIEW

**Review by aidai524 — CHANGES_REQUESTED** [review]
Hey @zavodil there will be a format error in this place, can you help to check if there is a problem? accumulated_volume: 'Накопичений об'єм, maybe 'Накопичений обєм'?

**Comment by zavodil** [comment]
I pushed with `&apos;`

**Comment by zavodil** [comment]
Hey @aidai524, is it fine now with the tag replacement?

**Comment by aidai524** [comment]
> Hey @aidai524, is it fine now with the tag replacement?

Hey @zavodil thanks for you update, based on your content, I made a small modification to format the text It should be fine now.

**Review by aidai524 — APPROVED** [review]

**Pull request merged**
