### PR TITLE
fix swap DISK token error

### PR DESCRIPTION
**Pull request by aidai524**
fix swap action when min_amount_out is not integer

### CODE REVIEW

**Review by marco-sundsk — APPROVED** [review]
OK, let's go testing it.

**Review by mehtaphysical — CHANGES_REQUESTED** [review]
Should fix `toNonDivisibleNumber` which should never return a decimal number

**Comment by aidai524** [comment]
> Should fix `toNonDivisibleNumber` which should never return a decimal number
My idea is to deal with when toNonDivisibleNumber result is a decimal, if not, keep the original value.This will have no effect on tokens that have no precision problems.

**Comment by mehtaphysical** [comment]
> > My idea is to deal with when toNonDivisibleNumber result is a decimal, if not, keep the original value.This will have no effect on tokens that have no precision problems.

But `toNonDivisibleNumber` should never result in a decimal. If it does, then that is a bug that should be fixed with that function.

**Pull request closed without merging**
